# Performance
repaint_delay                   6
input_delay                     1
sync_to_monitor                 yes

# Font settings
font_family                     Hack Nerd Font
font_features                   Hack Nerd Font +cv04 +cv10 +ss04 +ss03 +cv25 +cv32 +cv28 +ss06 +ss07
bold_font                       Hack Nerd Font
italic_font                     auto
bold_italic_font                auto
font_size                       10.0
disable_ligatures               never
# adjust_line_height              1

# Mouse
copy_on_select                  yes
strip_trailing_spaces           always

# Cursor
cursor_shape                    block
cursor_blink_interval           0

# Window layout
window_border_width             1px
hide_window_decorations         no

# Bell
enable_audio_bell               no
window_alert_on_bell            yes
bell_on_tab                     no

# # Tab Bar
# tab_bar_edge                    bottom
# tab_bar_style                   powerline
# tab_powerline_style             angled
# tab_bar_min_tabs                1
# tab_bar_align                   left

# Advance
shell_integration               enabled no-cursor
update_check_interval           0

# ####### Keyboard Shortcuts #######
#
# ## Misc
# # map alt+ctrl+shift+g launch --cwd=current gitui
#
# ## Tab management
# map alt+c new_tab
# map kitty_mod+enter new_tab
#
# map alt+1 goto_tab 1
# map alt+2 goto_tab 2
# map alt+3 goto_tab 3
# map alt+4 goto_tab 4
# map alt+5 goto_tab 5
# map alt+6 goto_tab 6
# map alt+7 goto_tab 7
# map alt+8 goto_tab 8
# map alt+9 goto_tab 9
#
# ## Window management
# map alt+enter new_window_with_cwd
#
# map alt+v toggle_layout tall
# map alt+s toggle_layout grid
#
# map alt+h neighboring_window left
# map alt+j neighboring_window bottom
# map alt+k neighboring_window top
# map alt+l neighboring_window right
#
# map alt+shift+h move_window left
# map alt+shift+j move_window bottom
# map alt+shift+k move_window top
# map alt+shift+l move_window right
#
# # map alt+shift+1 move_window left
# # map alt+shift+2 move_window bottom
# # map alt+shift+3 move_window top
# # map alt+shift+4 move_window right
# # map alt+shift+5 move_window right
# # map alt+shift+6 move_window right
# # map alt+shift+7 move_window right
# # map alt+shift+8 move_window right
# # map alt+shift+9 move_window right
# map kitty_mod+f4 detach_window ask
## name: Rosé Pine
## author: mvllow
## license: MIT
## upstream: https://github.com/rose-pine/kitty/blob/main/dist/rose-pine.conf
## blurb: All natural pine, faux fur and a bit of soho vibes for the classy minimalist

foreground               #e0def4
background               #191724
selection_foreground     #e0def4
selection_background     #403d52

cursor                   #524f67
cursor_text_color        #e0def4

url_color                #c4a7e7

active_tab_foreground    #e0def4
active_tab_background    #26233a
inactive_tab_foreground  #6e6a86
inactive_tab_background  #191724

active_border_color      #31748f
inactive_border_color    #403d52

# black
color0   #26233a
color8   #6e6a86

# red
color1   #eb6f92
color9   #eb6f92

# green
color2   #31748f
color10  #31748f

# yellow
color3   #f6c177
color11  #f6c177

# blue
color4   #9ccfd8
color12  #9ccfd8

# magenta
color5   #c4a7e7
color13  #c4a7e7

# cyan
color6   #ebbcba
color14  #ebbcba

# white
color7   #e0def4
color15  #e0def4
